version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID:"10355467" # Your API HASH from my.telegram.org
      API_HASH: "d86087c1892f818da03d68c3eaba765c" # Your API ID from my.telegram.org
      BOT_TOKEN: "7895637713:AAFW2Flj4AmiglOOsd9k8HozbMZgOhR1IVg" # Bot token, get it from @BotFather 
      SESSION: # Pyrogram string session
      AUTH: # User ID of Bot owner
      FORCESUB: # Username name of public channel without using '@'
